name: Daily Startup Pipeline

on:
  schedule:
    - cron: '30 2 * * *'  # 8am IST
  workflow_dispatch:        # manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean install
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        run: |
          nvm install 20
          nvm use 20
          node --version

      - name: Install dependencies
        run: npm install
      - name: Patch undici
        run: |
          find . -path ./node_modules/undici/lib/web/webidl/index.js | xargs sed -i 's/webidl.is.File = webidl.util.MakeTypeAssertion(File)/webidl.is.File = () => false/g'
      - name: Run pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node pipeline.js